"""Tests for the CRYSTAL ``.d12`` input-deck generator (needs pymatgen)."""

import numpy as np
import pytest

from crystalline.core.crystal_input import (
    AnhapesOptions,
    AnharmOptions,
    BasisOptions,
    CphfOptions,
    CrystalInputError,
    CrystalInputSpec,
    DispersionOptions,
    ElasticOptions,
    EosOptions,
    FreqOptions,
    GeometryOptions,
    MethodOptions,
    OptGeomOptions,
    QhaOptions,
    ScfOptions,
    TaskOptions,
    TwoComponentOptions,
    build_input,
    suggest_shrink,
    tolinteg_warnings,
    write_input,
)
from crystalline.core.structure import Structure

pytest.importorskip("pymatgen")
from ase import Atoms  # noqa: E402
from ase.build import bulk  # noqa: E402
from ase.spacegroup import crystal as ase_crystal  # noqa: E402


def _lines(deck: str) -> list[str]:
    return deck.splitlines()


def _nacl() -> Structure:
    return Structure.from_ase(bulk("NaCl", "rocksalt", a=5.64))


def _rutile() -> Structure:
    atoms = ase_crystal(
        ["Ti", "O"],
        basis=[(0, 0, 0), (0.305, 0.305, 0.0)],
        spacegroup=136,
        cellpar=[4.59, 4.59, 2.96, 90, 90, 90],
    )
    return Structure.from_ase(atoms)


def _co_molecule() -> Structure:
    mol = Structure.empty()
    mol.add_atom("C", [0.0, 0.0, 0.0])
    mol.add_atom("O", [0.0, 0.0, 1.128])
    return mol


# ── geometry block: 3D crystals ────────────────────────────────────────────
def test_nacl_geometry_is_symmetry_reduced_cubic():
    deck = build_input(_nacl())
    lines = _lines(deck)
    assert lines[0] == "Generated by CRYSTALLine"  # title
    assert lines[1] == "CRYSTAL"
    assert lines[2] == "0 0 0"  # IFLAG IFHR IFSO
    assert lines[3] == "225"  # space group Fm-3m
    assert lines[4] == "5.640000"  # cubic: a single "a" parameter
    assert lines[5] == "2"  # two atoms in the asymmetric unit (Na, Cl)
    # the two irreducible atoms are Na (11) and Cl (17)
    zs = sorted(int(lines[6 + i].split()[0]) for i in range(2))
    assert zs == [11, 17]


def test_rutile_prints_a_and_c_for_tetragonal():
    deck = build_input(_rutile())
    lines = _lines(deck)
    assert lines[1] == "CRYSTAL"
    assert lines[3] == "136"  # P4_2/mnm
    # tetragonal -> minimal set is (a, c): two numbers on the lattice line
    latt = lines[4].split()
    assert len(latt) == 2
    assert abs(float(latt[0]) - 4.59) < 1e-2 and abs(float(latt[1]) - 2.96) < 1e-2
    assert lines[5] == "2"  # Ti and O irreducible


def test_symmetry_off_writes_p1_with_every_atom():
    deck = build_input(_nacl(), CrystalInputSpec(geometry=GeometryOptions(use_symmetry=False)))
    lines = _lines(deck)
    assert lines[3] == "1"  # space group P1
    # triclinic P1 lists the full minimal set (six numbers) ...
    assert len(lines[4].split()) == 6
    # ... and every atom of the (primitive) cell, not just the asymmetric unit
    n_atoms = int(lines[5])
    assert n_atoms == len(_nacl())


# ── geometry block: 0D molecule ────────────────────────────────────────────
def test_molecule_uses_molecule_keyword_and_cartesian():
    deck = build_input(_co_molecule())
    lines = _lines(deck)
    assert lines[1] == "MOLECULE"
    assert lines[2] == "1"  # point group C1
    assert lines[3] == "2"  # two atoms
    # cartesian coords in Angstrom: O sits at z = 1.128
    o_line = lines[5].split()
    assert int(o_line[0]) == 8 and abs(float(o_line[3]) - 1.128) < 1e-6
    # a molecule has no k-mesh
    assert "SHRINK" not in deck


# ── geometry block: 2D slabs and 1D polymers ───────────────────────────────
def _slab(pbc=(True, True, False)) -> Structure:
    """A two-atom MgO-like slab; ``pbc`` picks which direction is the vacuum."""
    cell = np.diag([4.21, 4.21, 4.21])
    aperiodic = pbc.index(False)
    cell[aperiodic, aperiodic] = 500.0  # CRYSTAL's formal vacuum thickness
    periodic = [i for i, p in enumerate(pbc) if p]
    second = np.zeros(3)
    second[periodic[0]] = second[periodic[1]] = 2.105
    return Structure.from_ase(
        Atoms("MgO", positions=[[0, 0, 0], second], cell=cell, pbc=pbc)
    )


def _polymer(pbc=(True, False, False)) -> Structure:
    """A CH2 repeat unit; ``pbc`` picks which direction is the chain axis."""
    cell = np.diag([500.0, 500.0, 500.0])
    axis = pbc.index(True)
    cell[axis, axis] = 2.5
    others = [i for i in range(3) if i != axis]
    h1, h2 = np.zeros(3), np.zeros(3)
    h1[axis] = h2[axis] = 0.6
    h1[others[0]] = 0.9
    h2[others[0]] = -0.9
    return Structure.from_ase(
        Atoms("CH2", positions=[[0, 0, 0], h1, h2], cell=cell, pbc=pbc)
    )


def test_slab_uses_layer_group_1_with_in_plane_parameters():
    lines = _lines(build_input(_slab()))
    assert lines[1] == "SLAB"
    assert lines[2] == "1"  # layer group p1
    assert lines[3] == "4.210000 4.210000 90.000000"  # a, b, gamma
    assert lines[4] == "2"


def test_slab_coordinates_are_fractional_in_plane_and_angstrom_out_of_plane():
    lines = _lines(build_input(_slab()))
    mg, o = lines[5].split(), lines[6].split()
    assert int(mg[0]) == 12 and int(o[0]) == 8
    # the second atom sits at half the cell along both periodic directions ...
    assert abs(float(o[1]) - 0.5) < 1e-9 and abs(float(o[2]) - 0.5) < 1e-9
    # ... and both atoms lie in the plane, so z is 0 Angstrom (not fractional)
    assert abs(float(mg[3])) < 1e-9 and abs(float(o[3])) < 1e-9


def test_slab_with_another_vacuum_axis_is_rotated_into_the_xy_plane():
    # CRYSTAL requires the slab in xy; an x- or y-aperiodic cell must be rotated,
    # and must give the same deck as the already-oriented one.
    reference = _lines(build_input(_slab((True, True, False))))[1:]
    for pbc in ((False, True, True), (True, False, True)):
        assert _lines(build_input(_slab(pbc)))[1:] == reference


def test_polymer_uses_rod_group_1_and_one_lattice_parameter():
    lines = _lines(build_input(_polymer()))
    assert lines[1] == "POLYMER"
    assert lines[2] == "1"  # rod group p1
    assert lines[3] == "2.500000"  # the repeat length only
    assert lines[4] == "3"


def test_polymer_coordinates_are_fractional_along_x_only():
    lines = _lines(build_input(_polymer()))
    carbon, hydrogen = lines[5].split(), lines[6].split()
    assert int(carbon[0]) == 6 and int(hydrogen[0]) == 1
    # x is fractional: 0.6 A along a 2.5 A repeat
    assert abs(float(hydrogen[1]) - 0.24) < 1e-9
    # y and z stay in Angstrom
    assert abs(abs(float(hydrogen[2])) - 0.9) < 1e-9


def test_polymer_along_another_axis_keeps_its_repeat_length():
    for pbc in ((False, True, False), (False, False, True)):
        lines = _lines(build_input(_polymer(pbc)))
        assert lines[3] == "2.500000"
        # the chain-axis fraction survives the rotation
        assert abs(float(lines[6].split()[1]) - 0.24) < 1e-9


def test_reduced_dimensionality_has_a_k_mesh_but_no_3d_space_group():
    slab = build_input(_slab())
    assert "SHRINK" in slab  # still periodic
    assert "225" not in _lines(slab)


def test_empty_structure_raises():
    with pytest.raises(CrystalInputError):
        build_input(Structure.empty())


# ── basis + Hamiltonian block ──────────────────────────────────────────────
def test_basisset_card_terminates_geometry_and_names_library():
    deck = build_input(_nacl(), CrystalInputSpec(basis=BasisOptions(name="POB-DZVP")))
    lines = _lines(deck)
    i = lines.index("BASISSET")
    assert lines[i + 1] == "POB-DZVP"
    # BASISSET replaces block-1 END: no bare END before it
    assert "END" not in lines[:i]


def test_dft_block_with_functional_and_default_shrink():
    deck = build_input(_nacl())  # defaults: DFT / PBE0
    lines = _lines(deck)
    d = lines.index("DFT")
    assert lines[d + 1] == "PBE0"
    assert lines[d + 2] == "END"  # DFT sub-block closed
    assert "SHRINK" in lines
    assert lines[-1] == "END"  # block 3 closed


def test_hartree_fock_has_no_dft_block():
    deck = build_input(_nacl(), CrystalInputSpec(method=MethodOptions(kind="HF")))
    assert "DFT" not in _lines(deck)
    assert "SHRINK" in deck  # still periodic


def test_dispersion_appends_d3_suffix_only_for_parametrised_functionals():
    d3 = build_input(
        _nacl(), CrystalInputSpec(method=MethodOptions(functional="PBE0", dispersion_d3=True))
    )
    assert "PBE0-D3" in d3
    # a functional CRYSTAL hasn't D3-parametrised is left untouched
    plain = build_input(
        _nacl(), CrystalInputSpec(method=MethodOptions(functional="PBESOL0", dispersion_d3=True))
    )
    assert "PBESOL0-D3" not in plain
    assert "PBESOL0" in plain


def test_spin_polarized_dft_adds_spin_hf_adds_uhf():
    dft = build_input(_nacl(), CrystalInputSpec(scf=ScfOptions(spin_polarized=True)))
    assert "SPIN" in _lines(dft)
    hf = build_input(
        _nacl(),
        CrystalInputSpec(method=MethodOptions(kind="HF"), scf=ScfOptions(spin_polarized=True)),
    )
    assert "UHF" in _lines(hf)


# ── task block ─────────────────────────────────────────────────────────────
def test_single_point_has_no_optgeom_and_toldee_6():
    lines = _lines(build_input(_nacl()))
    assert "OPTGEOM" not in lines
    assert lines[lines.index("TOLDEE") + 1] == "6"


def test_optgeom_defaults_to_full_relaxation_without_extra_keyword():
    # CRYSTAL optimises cell + atoms by default, so no FULLOPTG/ATOMONLY is emitted.
    deck = build_input(_nacl(), CrystalInputSpec(task=TaskOptions(kind="OPTGEOM")))
    lines = _lines(deck)
    assert lines[lines.index("OPTGEOM") + 1] == "ENDOPT"
    assert "FULLOPTG" not in lines
    assert "ATOMONLY" not in lines
    # OPTGEOM must precede BASISSET (it lives in block 1)
    assert lines.index("OPTGEOM") < lines.index("BASISSET")
    # OPTGEOM raises the SCF energy tolerance default to 7
    assert lines[lines.index("TOLDEE") + 1] == "7"


def test_optgeom_atoms_only_emits_atomonly():
    deck = build_input(
        _nacl(), CrystalInputSpec(task=TaskOptions(kind="OPTGEOM", optimize_cell=False))
    )
    lines = _lines(deck)
    assert lines[lines.index("OPTGEOM") + 1] == "ATOMONLY"
    assert "FULLOPTG" not in lines


def test_freqcalc_block_before_basisset_with_toldee_10():
    deck = build_input(_nacl(), CrystalInputSpec(task=TaskOptions(kind="FREQCALC")))
    lines = _lines(deck)
    assert "FREQCALC" in lines
    assert lines.index("FREQCALC") < lines.index("BASISSET")
    assert lines[lines.index("FREQCALC") + 1] == "END"  # closes the FREQCALC block
    assert lines[lines.index("TOLDEE") + 1] == "10"  # frequency default


def test_freqcalc_ir_intensities_add_intens_inside_the_block():
    deck = build_input(
        _nacl(),
        CrystalInputSpec(task=TaskOptions(kind="FREQCALC", freq=FreqOptions(ir_intensities=True))),
    )
    lines = _lines(deck)
    i = lines.index("FREQCALC")
    # INTENS plus the default Berry-phase technique
    assert lines[i + 1 : i + 3] == ["INTENS", "INTPOL"]


def test_preoptimize_nests_a_fulloptg_preoptgeom_block():
    deck = build_input(
        _nacl(),
        CrystalInputSpec(
            task=TaskOptions(
                kind="FREQCALC", preoptimize=True, freq=FreqOptions(ir_intensities=True)
            )
        ),
    )
    lines = _lines(deck)
    i = lines.index("FREQCALC")
    assert lines[i + 1 : i + 5] == ["PREOPTGEOM", "FULLOPTG", "END", "INTENS"]
    # the FREQCALC block still closes before BASISSET
    assert lines.index("BASISSET") > i + 5


def test_eos_block_uses_toldee_8():
    deck = build_input(_nacl(), CrystalInputSpec(task=TaskOptions(kind="EOS")))
    lines = _lines(deck)
    assert lines[lines.index("EOS") + 1] == "END"
    assert lines.index("EOS") < lines.index("BASISSET")
    assert lines[lines.index("TOLDEE") + 1] == "8"


def test_elastcon_block_uses_toldee_8():
    deck = build_input(_nacl(), CrystalInputSpec(task=TaskOptions(kind="ELASTCON")))
    lines = _lines(deck)
    assert lines[lines.index("ELASTCON") + 1] == "END"
    assert lines.index("ELASTCON") < lines.index("BASISSET")
    assert lines[lines.index("TOLDEE") + 1] == "8"


# ── Raman / CPHF ───────────────────────────────────────────────────────────
def _freq_block(deck: str) -> list[str]:
    """The FREQCALC block's lines, from the keyword up to (not incl.) BASISSET."""
    lines = _lines(deck)
    return lines[lines.index("FREQCALC") : lines.index("BASISSET")]


def test_raman_forces_intens_and_the_intcphf_block():
    # The manual requires INTRAMAN to always accompany INTENS, with the Raman
    # tensor supplied by the CPHF block that INTCPHF opens.
    deck = build_input(
        _nacl(),
        CrystalInputSpec(task=TaskOptions(kind="FREQCALC", freq=FreqOptions(raman_intensities=True))),
    )
    block = _freq_block(deck)
    # exactly the manual's canonical minimal Raman block (§8.4)
    assert block == ["FREQCALC", "INTENS", "INTRAMAN", "INTCPHF", "END", "END"]


def test_raman_overrides_a_non_cphf_ir_technique():
    # Berry phase cannot produce a Raman tensor; INTCPHF must win.
    deck = build_input(
        _nacl(),
        CrystalInputSpec(
            task=TaskOptions(
                kind="FREQCALC",
                freq=FreqOptions(raman_intensities=True, ir_technique="INTPOL"),
            )
        ),
    )
    block = _freq_block(deck)
    assert "INTCPHF" in block and "INTPOL" not in block


def test_ir_technique_is_honoured_without_raman():
    deck = build_input(
        _nacl(),
        CrystalInputSpec(
            task=TaskOptions(
                kind="FREQCALC", freq=FreqOptions(ir_intensities=True, ir_technique="INTLOC")
            )
        ),
    )
    block = _freq_block(deck)
    assert block[1:3] == ["INTENS", "INTLOC"]
    assert "INTRAMAN" not in block


def test_intcphf_block_carries_cphf_keywords():
    deck = build_input(
        _nacl(),
        CrystalInputSpec(
            task=TaskOptions(
                kind="FREQCALC",
                freq=FreqOptions(
                    raman_intensities=True,
                    cphf=CphfOptions(fmixing=60, maxcycle=200, fmixing2=60, maxcycle2=200),
                ),
            )
        ),
    )
    block = _freq_block(deck)
    assert block.index("INTRAMAN") < block.index("INTCPHF")  # manual's ordering
    i = block.index("INTCPHF")
    assert block[i + 1 : i + 9] == [
        "FMIXING", "60", "MAXCYCLE", "200", "FMIXING2", "60", "MAXCYCLE2", "200",
    ]
    assert block[i + 9] == "END"  # INTCPHF block closed
    assert block[-1] == "END"  # FREQCALC block closed


def test_raman_experimental_conditions_and_spectra_blocks():
    deck = build_input(
        _nacl(),
        CrystalInputSpec(
            task=TaskOptions(
                kind="FREQCALC",
                freq=FreqOptions(
                    raman_intensities=True,
                    raman_experiment=(298.15, 532.0),
                    raman_spectrum=True,
                    ir_spectrum=True,
                ),
            )
        ),
    )
    block = _freq_block(deck)
    assert block[block.index("RAMANEXP") + 1] == "298.15 532"
    # RAMANEXP follows the INTCPHF block that supplies the tensor
    assert block.index("RAMANEXP") > block.index("INTCPHF")
    # each spectrum keyword opens a block closed by its own END
    assert block[block.index("IRSPEC") + 1] == "END"
    assert block[block.index("RAMSPEC") + 1] == "END"


def test_standalone_cphf_task_with_fourth_order():
    deck = build_input(
        _nacl(),
        CrystalInputSpec(task=TaskOptions(kind="CPHF", cphf=CphfOptions(order="FOURTH", maxcycle=80))),
    )
    lines = _lines(deck)
    i = lines.index("CPHF")
    assert lines[i : i + 5] == ["CPHF", "FOURTH", "MAXCYCLE", "80", "END"]
    assert lines.index("CPHF") < lines.index("BASISSET")
    assert lines[lines.index("TOLDEE") + 1] == "9"  # CPHF needs a tight SCF


def test_second_order_cphf_emits_no_order_keyword():
    deck = build_input(_nacl(), CrystalInputSpec(task=TaskOptions(kind="CPHF")))
    lines = _lines(deck)
    assert lines[lines.index("CPHF") + 1] == "END"


# ── per-block optional keywords ────────────────────────────────────────────
def test_freqcalc_numeric_controls():
    deck = build_input(
        _nacl(),
        CrystalInputSpec(
            task=TaskOptions(
                kind="FREQCALC",
                freq=FreqOptions(numderiv=2, stepsize=0.003, analysis=True, restart=True),
            )
        ),
    )
    block = _freq_block(deck)
    assert block[:8] == [
        "FREQCALC", "RESTART", "NUMDERIV", "2", "STEPSIZE", "0.003", "ANALYSIS", "END",
    ]


def test_freqcalc_temperature_and_pressure_ranges():
    deck = build_input(
        _nacl(),
        CrystalInputSpec(
            task=TaskOptions(
                kind="FREQCALC",
                freq=FreqOptions(temperature=(10, 100.0, 1000.0), pressure=(5, 0.1, 10.0)),
            )
        ),
    )
    block = _freq_block(deck)
    assert block[block.index("TEMPERAT") + 1] == "10 100 1000"
    assert block[block.index("PRESSURE") + 1] == "5 0.1 10"


def test_optgeom_convergence_keywords():
    deck = build_input(
        _nacl(),
        CrystalInputSpec(
            task=TaskOptions(
                kind="OPTGEOM", optgeom=OptGeomOptions(toldeg=0.0001, toldex=0.0004, maxcycle=200)
            )
        ),
    )
    lines = _lines(deck)
    i = lines.index("OPTGEOM")
    assert lines[i + 1 : i + 8] == [
        "TOLDEG", "0.0001", "TOLDEX", "0.0004", "MAXCYCLE", "200", "ENDOPT",
    ]


def test_eos_volume_and_pressure_ranges():
    deck = build_input(
        _nacl(),
        CrystalInputSpec(
            task=TaskOptions(
                kind="EOS", eos=EosOptions(volume_range=(0.9, 1.05, 10), pressure_range=(-5, 10, 20))
            )
        ),
    )
    lines = _lines(deck)
    i = lines.index("EOS")
    assert lines[i + 1 : i + 6] == ["RANGE", "0.9 1.05 10", "PRANGE", "-5 10 20", "END"]


def test_elastcon_options():
    deck = build_input(
        _nacl(),
        CrystalInputSpec(
            task=TaskOptions(
                kind="ELASTCON", elastic=ElasticOptions(numderiv=3, stepsize=0.01, clamped_ion=True)
            )
        ),
    )
    lines = _lines(deck)
    i = lines.index("ELASTCON")
    assert lines[i + 1 : i + 7] == ["NUMDERIV", "3", "STEPSIZE", "0.01", "CLAMPION", "END"]


def test_per_block_extra_keywords_land_inside_their_block():
    deck = build_input(
        _nacl(),
        CrystalInputSpec(
            task=TaskOptions(kind="FREQCALC", freq=FreqOptions(extra_keywords="NOECKART\nMODES"))
        ),
    )
    block = _freq_block(deck)
    assert block == ["FREQCALC", "NOECKART", "MODES", "END"]


# ── phonon dispersion ──────────────────────────────────────────────────────
def _cube() -> list:
    return [[2, 0, 0], [0, 2, 0], [0, 0, 2]]


def test_dispersion_is_a_freqcalc_block_with_dispersi():
    deck = build_input(_nacl(), CrystalInputSpec(task=TaskOptions(kind="DISPERSION")))
    lines = _lines(deck)
    # phonon dispersion has no keyword of its own: it is FREQCALC + DISPERSI
    assert "DISPERSION" not in lines
    i = lines.index("FREQCALC")
    assert lines[i : i + 3] == ["FREQCALC", "DISPERSI", "END"]
    assert lines[lines.index("TOLDEE") + 1] == "10"


def test_scelphono_precedes_the_task_block_and_writes_rows():
    deck = build_input(
        _nacl(), CrystalInputSpec(task=TaskOptions(kind="DISPERSION", supercell=_cube()))
    )
    lines = _lines(deck)
    i = lines.index("SCELPHONO")
    assert lines[i + 1 : i + 4] == ["2 0 0", "0 2 0", "0 0 2"]
    # SCELPHONO is a geometry keyword: it comes before FREQCALC
    assert i < lines.index("FREQCALC")


def test_scelphono_rejects_a_non_3x3_matrix():
    with pytest.raises(CrystalInputError, match="3×3"):
        build_input(_nacl(), CrystalInputSpec(task=TaskOptions(kind="QHA", supercell=[[2, 0, 0]])))


def test_dispersion_pdos_matches_the_manual_example():
    deck = build_input(
        _nacl(),
        CrystalInputSpec(
            task=TaskOptions(kind="DISPERSION", dispersion=DispersionOptions(pdos=(2500, 250, 1)))
        ),
    )
    lines = _lines(deck)
    i = lines.index("FREQCALC")
    assert lines[i : i + 6] == ["FREQCALC", "DISPERSI", "PDOS", "2500 250", "1", "END"]


def test_dispersion_ins_block():
    deck = build_input(
        _nacl(),
        CrystalInputSpec(
            task=TaskOptions(kind="DISPERSION", dispersion=DispersionOptions(ins=(3000, 300, 2)))
        ),
    )
    lines = _lines(deck)
    assert lines[lines.index("INS") : lines.index("INS") + 3] == ["INS", "3000 300", "2"]


def test_dispersion_interphess_and_wang():
    deck = build_input(
        _nacl(),
        CrystalInputSpec(
            task=TaskOptions(
                kind="DISPERSION",
                dispersion=DispersionOptions(
                    interphess=(4, 4, 4, 0), wang=[2.5, 0, 0, 0, 2.5, 0, 0, 0, 2.5]
                ),
            )
        ),
    )
    lines = _lines(deck)
    i = lines.index("INTERPHESS")
    assert lines[i + 1 : i + 3] == ["4 4 4", "0"]
    assert lines[lines.index("WANG") + 1] == "2.5 0 0 0 2.5 0 0 0 2.5"


def test_wang_needs_nine_tensor_elements():
    with pytest.raises(CrystalInputError, match="9 elements"):
        build_input(
            _nacl(),
            CrystalInputSpec(
                task=TaskOptions(kind="DISPERSION", dispersion=DispersionOptions(wang=[1.0, 2.0]))
            ),
        )


def test_dispersion_bands_counts_its_path_segments():
    deck = build_input(
        _nacl(),
        CrystalInputSpec(
            task=TaskOptions(
                kind="DISPERSION",
                dispersion=DispersionOptions(
                    bands=True,
                    bands_shrink=16,
                    bands_points=30,
                    bands_path="0 0 0  8 0 0\n8 0 0  8 8 0\n8 8 0  0 0 0",
                ),
            )
        ),
    )
    lines = _lines(deck)
    i = lines.index("BANDS")
    assert lines[i + 1] == "16 30 3"  # NLINE derived from the three segments
    assert lines[i + 2] == "0 0 0  8 0 0"


def test_bands_without_a_path_raises():
    with pytest.raises(CrystalInputError, match="path segment"):
        build_input(
            _nacl(),
            CrystalInputSpec(
                task=TaskOptions(kind="DISPERSION", dispersion=DispersionOptions(bands=True))
            ),
        )


def test_bands_implies_noksymdisp_so_it_is_not_written_twice():
    deck = build_input(
        _nacl(),
        CrystalInputSpec(
            task=TaskOptions(
                kind="DISPERSION",
                dispersion=DispersionOptions(bands=True, bands_path="0 0 0 8 0 0", noksymdisp=True),
            )
        ),
    )
    assert "NOKSYMDISP" not in _lines(deck)


# ── QHA ────────────────────────────────────────────────────────────────────
def test_qha_matches_the_manual_corundum_example():
    deck = build_input(
        _nacl(),
        CrystalInputSpec(
            task=TaskOptions(
                kind="QHA",
                supercell=[[1, -1, 0], [0, 1, -1], [1, 1, 1]],
                qha=QhaOptions(temperature=(100, 10, 1200)),
            )
        ),
    )
    lines = _lines(deck)
    i = lines.index("SCELPHONO")
    assert lines[i : i + 8] == [
        "SCELPHONO", "1 -1 0", "0 1 -1", "1 1 1", "QHA", "TEMPERAT", "100 10 1200", "END",
    ]


def test_qha_step_and_points():
    deck = build_input(
        _nacl(), CrystalInputSpec(task=TaskOptions(kind="QHA", qha=QhaOptions(step=3.5, points=7)))
    )
    lines = _lines(deck)
    i = lines.index("QHA")
    assert lines[i : i + 6] == ["QHA", "STEP", "3.5", "POINTS", "7", "END"]


def test_qha_volume_range_and_restart():
    deck = build_input(
        _nacl(),
        CrystalInputSpec(
            task=TaskOptions(kind="QHA", qha=QhaOptions(volume_range=(0.94, 1.06, 7), restart2=True))
        ),
    )
    lines = _lines(deck)
    assert "RESTART2" in lines
    assert lines[lines.index("VRANGE") + 1] == "0.94 1.06 7"


def test_qha_supports_preoptimisation():
    deck = build_input(_nacl(), CrystalInputSpec(task=TaskOptions(kind="QHA", preoptimize=True)))
    lines = _lines(deck)
    i = lines.index("QHA")
    assert lines[i + 1 : i + 4] == ["PREOPTGEOM", "FULLOPTG", "END"]


# ── anharmonic: ANHAPES / VSCF / VCI ───────────────────────────────────────
_MODES = "4 5 6 7 8 9 10 11 12 13 14 15"


def test_anhapes_matches_the_manual_vci_example():
    deck = build_input(
        _nacl(),
        CrystalInputSpec(
            task=TaskOptions(
                kind="ANHAPES",
                anhapes=AnhapesOptions(modes=_MODES, scheme=3, step=0.9, vci=True),
            )
        ),
    )
    lines = _lines(deck)
    i = lines.index("FREQCALC")
    assert lines[i : i + 9] == [
        "FREQCALC", "ANHAPES", "12", _MODES, "3 0.9", "VCI", "6 3", "1", "END",
    ]
    assert lines[lines.index("TOLDEE") + 1] == "10"


def test_anhapes_restarts_and_vscf_tuning():
    deck = build_input(
        _nacl(),
        CrystalInputSpec(
            task=TaskOptions(
                kind="ANHAPES",
                anhapes=AnhapesOptions(
                    modes=_MODES, restart=True, restart_pes=True,
                    vscf=True, vscf_tol=5, vscf_mix=40,
                ),
            )
        ),
    )
    lines = _lines(deck)
    i = lines.index("FREQCALC")
    assert lines[i + 1 : i + 3] == ["RESTART", "RESTPES"]  # both precede ANHAPES
    assert lines[lines.index("VSCFTOL") + 1] == "5"
    assert lines[lines.index("VSCFMIX") + 1] == "40"


def test_vci_does_not_also_write_vscf():
    # VCI performs a VSCF of its own, so VSCF is written only when asked for.
    deck = build_input(
        _nacl(),
        CrystalInputSpec(task=TaskOptions(kind="ANHAPES", anhapes=AnhapesOptions(modes=_MODES, vci=True))),
    )
    assert "VSCF" not in _lines(deck)


def test_anhapes_rejects_translational_modes():
    with pytest.raises(CrystalInputError, match="translations"):
        build_input(
            _nacl(),
            CrystalInputSpec(task=TaskOptions(kind="ANHAPES", anhapes=AnhapesOptions(modes="1 2 3 7"))),
        )


def test_anhapes_rejects_an_empty_or_malformed_mode_list():
    with pytest.raises(CrystalInputError, match="at least one mode"):
        build_input(_nacl(), CrystalInputSpec(task=TaskOptions(kind="ANHAPES")))
    with pytest.raises(CrystalInputError, match="integers"):
        build_input(
            _nacl(),
            CrystalInputSpec(task=TaskOptions(kind="ANHAPES", anhapes=AnhapesOptions(modes="4 x"))),
        )


def test_anhapes_accepts_comma_and_newline_separated_modes():
    deck = build_input(
        _nacl(),
        CrystalInputSpec(task=TaskOptions(kind="ANHAPES", anhapes=AnhapesOptions(modes="4, 5\n6"))),
    )
    lines = _lines(deck)
    i = lines.index("ANHAPES")
    assert lines[i + 1 : i + 3] == ["3", "4 5 6"]


# ── anharmonic: ANHARM (X–H stretching) ────────────────────────────────────
def test_anharm_is_a_standalone_block_not_inside_freqcalc():
    deck = build_input(
        _nacl(), CrystalInputSpec(task=TaskOptions(kind="ANHARM", anharm=AnharmOptions(atom_label=5)))
    )
    lines = _lines(deck)
    assert "FREQCALC" not in lines  # no harmonic run is needed for ANHARM
    i = lines.index("ANHARM")
    assert lines[i : i + 3] == ["ANHARM", "5", "END"]
    assert lines.index("ANHARM") < lines.index("BASISSET")


def test_anharm_options_and_isotopes():
    deck = build_input(
        _nacl(),
        CrystalInputSpec(
            task=TaskOptions(
                kind="ANHARM",
                anharm=AnharmOptions(
                    atom_label=5, keepsymm=True, points26=True, isotopes=[(5, 2.0)]
                ),
            )
        ),
    )
    lines = _lines(deck)
    i = lines.index("ANHARM")
    assert lines[i : i + 7] == ["ANHARM", "5", "KEEPSYMM", "POINTS26", "ISOTOPES", "1", "5 2"]


def test_anharm_rejects_a_bad_atom_label():
    with pytest.raises(CrystalInputError, match="hydrogen"):
        build_input(
            _nacl(),
            CrystalInputSpec(task=TaskOptions(kind="ANHARM", anharm=AnharmOptions(atom_label=0))),
        )


# ── functional: combined vs separate exchange / correlation ────────────────
def test_split_functional_writes_exchange_and_correlat():
    deck = build_input(
        _nacl(),
        CrystalInputSpec(
            method=MethodOptions(functional_mode="SPLIT", exchange="BECKE", correlation="LYP")
        ),
    )
    lines = _lines(deck)
    i = lines.index("DFT")
    assert lines[i + 1 : i + 6] == ["EXCHANGE", "BECKE", "CORRELAT", "LYP", "END"]


def test_split_functional_rebuilds_b3lyp_from_parts():
    # The manual documents B3LYP as this exact sequence (§4.1).
    deck = build_input(
        _nacl(),
        CrystalInputSpec(
            method=MethodOptions(
                functional_mode="SPLIT", exchange="BECKE", correlation="LYP",
                hybrid_percent=20, nonlocal_weights=(0.9, 0.81),
            )
        ),
    )
    lines = _lines(deck)
    i = lines.index("DFT")
    assert lines[i + 1 : i + 10] == [
        "EXCHANGE", "BECKE", "CORRELAT", "LYP", "HYBRID", "20", "NONLOCAL", "0.9 0.81", "END",
    ]


def test_exchange_only_and_correlation_only_are_both_valid():
    # No CORRELAT is an exchange-only functional; no EXCHANGE keeps HF exchange.
    x_only = build_input(
        _nacl(), CrystalInputSpec(method=MethodOptions(functional_mode="SPLIT", exchange="PBE"))
    )
    assert "CORRELAT" not in _lines(x_only)
    c_only = build_input(
        _nacl(), CrystalInputSpec(method=MethodOptions(functional_mode="SPLIT", correlation="PWGGA"))
    )
    assert "EXCHANGE" not in _lines(c_only)
    assert "CORRELAT" in _lines(c_only)


def test_split_mode_needs_at_least_one_potential():
    with pytest.raises(CrystalInputError, match="exchange or a correlation"):
        build_input(_nacl(), CrystalInputSpec(method=MethodOptions(functional_mode="SPLIT")))


def test_combined_mode_still_writes_a_single_keyword():
    lines = _lines(build_input(_nacl()))
    i = lines.index("DFT")
    assert lines[i + 1 : i + 3] == ["PBE0", "END"]


def test_hybrid_percentage_applies_to_a_combined_functional_too():
    deck = build_input(
        _nacl(), CrystalInputSpec(method=MethodOptions(functional="PBE0", hybrid_percent=30))
    )
    assert _lines(deck)[_lines(deck).index("HYBRID") + 1] == "30"


# ── spin–orbit coupling / two-component SCF ────────────────────────────────
def test_twocompon_block_precedes_the_dft_block():
    deck = build_input(
        _nacl(),
        CrystalInputSpec(two_component=TwoComponentOptions(enabled=True, soc=True)),
    )
    lines = _lines(deck)
    i = lines.index("TWOCOMPON")
    assert lines[i : i + 3] == ["TWOCOMPON", "SOC", "END"]
    assert i < lines.index("DFT")


def test_noncollinear_keyword_goes_inside_the_dft_block():
    deck = build_input(
        _nacl(),
        CrystalInputSpec(
            method=MethodOptions(functional="PBE0"),
            two_component=TwoComponentOptions(enabled=True, soc=True, noncollinear="NONCOLC"),
        ),
    )
    lines = _lines(deck)
    i = lines.index("DFT")
    assert lines[i + 1 : i + 4] == ["NONCOLC", "PBE0", "END"]


def test_second_variational_writes_its_rotation_angles():
    deck = build_input(
        _nacl(),
        CrystalInputSpec(
            two_component=TwoComponentOptions(
                enabled=True, soc=True, second_variational=True,
                second_variational_rot=1, second_variational_angles=(90.0, 90.0),
            )
        ),
    )
    lines = _lines(deck)
    i = lines.index("2NDVARIAT")
    assert lines[i + 1 : i + 3] == ["1", "90 90"]


def test_second_variational_without_rotation_omits_angles():
    deck = build_input(
        _nacl(),
        CrystalInputSpec(
            two_component=TwoComponentOptions(enabled=True, soc=True, second_variational=True)
        ),
    )
    lines = _lines(deck)
    assert lines[lines.index("2NDVARIAT") + 1] == "0"
    assert lines[lines.index("2NDVARIAT") + 2] == "END"


def test_two_component_guess_and_spinorlock():
    deck = build_input(
        _nacl(),
        CrystalInputSpec(
            two_component=TwoComponentOptions(
                enabled=True, guess="GCOREROT", guess_angles=(90.0, 0.0), spinorlock=(8, 10)
            )
        ),
    )
    lines = _lines(deck)
    assert lines[lines.index("GCOREROT") + 1] == "90 0"
    assert lines[lines.index("SPINORLOCK") + 1] == "8 10"


def test_default_guess_is_not_written():
    deck = build_input(_nacl(), CrystalInputSpec(two_component=TwoComponentOptions(enabled=True)))
    assert "GUESSPAT" not in _lines(deck)  # it is CRYSTAL's default


def test_two_component_rejects_tasks_it_cannot_do():
    with pytest.raises(CrystalInputError, match="single-point"):
        build_input(
            _nacl(),
            CrystalInputSpec(
                two_component=TwoComponentOptions(enabled=True, soc=True),
                task=TaskOptions(kind="OPTGEOM"),
            ),
        )


def test_two_component_rejects_meta_gga_and_range_separated_functionals():
    with pytest.raises(CrystalInputError, match="meta-GGA or range-separated"):
        build_input(
            _nacl(),
            CrystalInputSpec(
                method=MethodOptions(functional="HSE06"),
                two_component=TwoComponentOptions(enabled=True, soc=True),
            ),
        )
    # a global hybrid LDA/GGA is fine
    build_input(
        _nacl(),
        CrystalInputSpec(
            method=MethodOptions(functional="PBE0"),
            two_component=TwoComponentOptions(enabled=True, soc=True),
        ),
    )


# ── SUPERCEL ───────────────────────────────────────────────────────────────
def test_supercel_is_written_in_the_geometry_block():
    deck = build_input(
        _nacl(), CrystalInputSpec(geometry=GeometryOptions(supercell=_cube()))
    )
    lines = _lines(deck)
    i = lines.index("SUPERCEL")
    assert lines[i + 1 : i + 4] == ["2 0 0", "0 2 0", "0 0 2"]
    assert i < lines.index("BASISSET")


def test_noshift_precedes_supercel():
    deck = build_input(
        _nacl(),
        CrystalInputSpec(geometry=GeometryOptions(supercell=_cube(), supercell_noshift=True)),
    )
    lines = _lines(deck)
    assert lines[lines.index("SUPERCEL") - 1] == "NOSHIFT"


def test_supercel_and_scelphono_cannot_be_combined():
    with pytest.raises(CrystalInputError, match="cannot be combined"):
        build_input(
            _nacl(),
            CrystalInputSpec(
                geometry=GeometryOptions(supercell=_cube()),
                task=TaskOptions(kind="DISPERSION", supercell=_cube()),
            ),
        )


def test_supercel_rejects_a_non_3x3_matrix():
    with pytest.raises(CrystalInputError, match="3×3"):
        build_input(_nacl(), CrystalInputSpec(geometry=GeometryOptions(supercell=[[2, 0, 0]])))


# ── TOLINTEG ───────────────────────────────────────────────────────────────
def test_tolinteg_is_written_from_the_spec():
    deck = build_input(_nacl(), CrystalInputSpec(scf=ScfOptions(tolinteg=(8, 8, 8, 8, 16))))
    lines = _lines(deck)
    assert lines[lines.index("TOLINTEG") + 1] == "8 8 8 8 16"


def test_tolinteg_defaults_are_the_manual_values():
    lines = _lines(build_input(_nacl()))
    assert lines[lines.index("TOLINTEG") + 1] == "7 7 7 7 14"


def test_tolinteg_warns_when_itol5_is_too_close_to_itol4():
    assert tolinteg_warnings((7, 7, 7, 7, 14)) == []
    assert tolinteg_warnings((7, 7, 7, 7, 8)) != []  # gap of 1 < 3
    assert "ITOL5" in tolinteg_warnings((7, 7, 7, 7, 8))[0]


def test_tolinteg_warns_on_bad_shape_or_values():
    assert tolinteg_warnings((7, 7, 7)) != []
    assert tolinteg_warnings((7, 7, 7, 0, 14)) != []


# ── misc ───────────────────────────────────────────────────────────────────
def test_extra_keywords_appended_before_final_end():
    deck = build_input(_nacl(), CrystalInputSpec(extra_keywords="BIPOSIZE\n9000000"))
    lines = _lines(deck)
    assert "BIPOSIZE" in lines
    assert lines.index("BIPOSIZE") < len(lines) - 1  # not the last line
    assert lines[-1] == "END"


def test_shrink_suggestion_scales_inversely_with_cell_size():
    small = suggest_shrink(_nacl())
    big = suggest_shrink(Structure.from_ase(bulk("NaCl", "rocksalt", a=15.0)))
    assert small > big >= 2


def test_missing_basis_name_raises():
    with pytest.raises(CrystalInputError):
        build_input(_nacl(), CrystalInputSpec(basis=BasisOptions(name="  ")))


def test_write_input_roundtrips_to_file(tmp_path):
    path = tmp_path / "nacl.d12"
    write_input(_nacl(), str(path))
    text = path.read_text()
    assert text.endswith("\n")
    assert text.splitlines()[1] == "CRYSTAL"


def test_deck_ends_with_single_trailing_newline():
    deck = build_input(_nacl())
    assert deck.endswith("\n") and not deck.endswith("\n\n")
